### ISSUE TITLE
Update runtime to version 40

### ISSUE THREAD

**Issue by FakeShemp** [flathub/com.leinardi.gwe#28]
The org.gnome.Platform runtime could now be updated to version 40.

**Comment by leinardi** [comment]
Do you know if it is backward compatible with GTK3 or if requires a migration of the GTK4?

**Comment by hfiguiere** [comment]
GNOME 40 is just the release after 3.38, nothing radically different. Usually it is just a matter of bumping the version in the manifest.

**Comment by mamoit** [comment]
Today I got the following warning:
```
Info: org.gnome.Sdk//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.leinardi.gwe
```
So `3.38` is now EOL.

**Comment by mamoit** [comment]
@leinardi just did a build with gnome 40 on #29.
Tried it and it seems to work straight out of the box.

**Comment by leinardi** [comment]
@mamoit  thank you for the PR, this weekend I'll upgrade some other dependencies and make a new release :+1:

**Comment by leinardi** [comment]
A new release will be up soon with the runtime version 40!
