### ISSUE TITLE
GNOME 40 runtime is no longer supported

### ISSUE THREAD

**Issue by mikejaques** [flathub/com.leinardi.gwe#31]
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.leinardi.gwe

**Comment by leinardi** [comment]
On it..

**Comment by leinardi** [comment]
Done.
